modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory
license="GNU General Public License"
[[mods]] #mandatory
modId="charcoal_pit" #mandatory
version="2.34" #mandatory
displayName="Charcoal Pit" #mandatory
credits="Terrafirmacraft" #optional
authors="EnderiumSmith, [TeamMoeg] dashuaibia" #optional
description='''

'''
[[dependencies.charcoal_pit]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.charcoal_pit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4,1.17)"
    ordering="NONE"
    side="BOTH"
